### ISSUE TITLE
Tkinter: Make all images stick to the left

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/cmdlaunch#7]
See App Icons, images are centered, make them stick to the left

**Comment by h-ranjan1110** [comment]
Hi @Abdur-rahmaanJ , I have had a little experience with Tkinter before so i would like to work on this. 
This is my first time in open source .
Can i work on this ?

**Comment by Abdur-rahmaanJ** [comment]
yes!

**Comment by h-ranjan1110** [comment]
![Screenshot from 2019-08-01 01-00-55](https://user-images.githubusercontent.com/33145120/62242124-1eb5c100-b3f8-11e9-8f8b-e6a58e18d318.png)
As I can see the images in App icons are already on the left.
Do you want it to be changed?

**Comment by Abdur-rahmaanJ** [comment]
hum weird, but if you want to contribute something, make a simple game with appropriate icon that can be launched through it!

**Comment by h-ranjan1110** [comment]
I do not have experience with making a game but I can add a program to generate a flower type pattern.
I am making a pull request for you to see.
